export const LOG_CREATE_REQUEST = 'LOG_CREATE_REQUEST'
export const LOG_CREATE_SUCCESS = 'LOG_CREATE_SUCCESS'
export const LOG_CREATE_FAIL = 'LOG_CREATE_FAIL'
export const LOG_CREATE_RESET = 'LOG_CREATE_RESET'
